classDiagram
    Person --> Doctor
    Person --> Patient
    Patient --> ChildPatient
    Patient --> AdultPatient
    Patient --> MemberPatient

    Treatment --> PhysiotherapyTreatment
    Treatment --> MedicationTreatment
